### PR TITLE
Hotfix: fix error names, configs merging

### PR DESCRIPTION
**Pull request by kolyshkin**
1. Fix some known error names and the CI check for these.
2. Fix merging configs with the same key.

### CODE REVIEW

**Comment by kolyshkin** [comment]
Wait a minute; the last commit breaks config.Log:
> using config &{Components:[] FailOnWarnings:false FilterFile: FromFile: FromURL: InsecurePull:false Limit:-1 NodeScan: ContainerImageComponent: ContainerImage: OutputFile: OutputFormat:table Parallelism:5 PrintExceptions:true PullSecret: TimeLimit:1h0m0s Verbose:false ConfigFile:{FilterFiles:[] FilterDirs:[/lib/firmware /lib/modules /usr/lib/.build-id /usr/lib/firmware /usr/lib/grub /usr/lib/modules /usr/share/app-info /usr/share/doc /usr/share/fonts /usr/share/icons /usr/share/openshift /usr/src/plugins /rootfs /sysroot] FilterImages:[] PayloadIgnores:map[multus-cni-container:0xc00030c190 openshift-enterprise-pod-container:0xc000305a90 operator-lifecycle-manager-container:0xc000305b30 ose-egress-router-cni-container:0xc00030c2d0 ose-machine-config-operator-container:0xc000305f40 ose-multus-whereabouts-ipam-cni-container:0xc000305d60 ose-network-interface-bond-cni-container:0xc000305e00 ose-network-tools-container:0xc000305ea0 ose-node-container:0xc00030c000 ose-ovn-kubernetes-container:0xc00030c230] TagIgnores:map[] RPMIgnores:map[containernetworking-plugins:0xc0003059f0 cri-o:0xc00030c690 cri-tools:0xc00030c4b0 glibc:0xc000305770 glibc-common:0xc0003056d0 ignition:0xc00030c550 podman:0xc00030c5f0 podman-catatonit:0xc000305950 runc:0xc000305810 skopeo:0xc00030c730] ErrIgnores:[]}}


Will redo

**Comment by kolyshkin** [comment]
Fixed; ready for review.

**Comment by kolyshkin** [comment]
Rebased

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
