### PR TITLE
Add exceptions for OpenShift Virtualisation

### PR DESCRIPTION
**Pull request by dominikholler**

### CODE REVIEW

**Comment by rphillips** [comment]
@dominikholler Can you provide a link to the dockefiles?

**Review by kolyshkin — CHANGES_REQUESTED** [review]
@dominikholler perhaps it's better to add this into global config instead? This will result in 4x decrease in amount of lines added :)

**Comment by dominikholler** [comment]
> @dominikholler Can you provide a link to the dockerfiles?

https://catalog.redhat.com/software/containers/container-native-virtualization/virt-cdi-importer-rhel9/633ffae45e9aa29cb935ca72?architecture=amd64&image=6601ae2c16b1b63a2fb91a41&container-tabs=dockerfile

https://catalog.redhat.com/software/containers/container-native-virtualization/virt-launcher-rhel9/633ffae66804229d44d4c75a?architecture=amd64&image=65eb469817260331dcb562ef

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
